#!/bin/bash

movenum=0
towersofh()
{
	if [ $1 -gt 0 ] ; 
		then
		towersofh "$(($1-1))" $2 $4 $3
		echo "Move disk(s) from tower" $2 "to tower" $3
		movenum=$(( $movenum + 1 ))
		towersofh "$(($1-1))" $4 $3 $2 
	fi   
}

echo "Enter the number of disks on the Towers of Hanoi: "
read disks
towersofh $disks 1 2 3
echo "Total of $movenum moves made"


